[package]
name = "starknet-hint-vrf"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ec = "0.4.2"
cairo-lang-runner = { git = "https://github.com/reilabs/cairo", branch = "2.6.3-hints" }
stark-vrf = { git = "https://github.com/reilabs/starknet-vrf" }
starknet-ff = "0.3.7"
